### ISSUE TITLE
No readme, no content, bad repo, unfollowed :P

### ISSUE THREAD

**Issue by CptPie** [codewith-luke/disclone#1]
o/ luke

**Comment by Thellior** [comment]
Is this finished yet?

**Comment by kayandra** [comment]
> o/ luke

creative and useful issues like this is what everyone should learn to emulate and be inspired by.

**Comment by kayandra** [comment]
> Is this finished yet?

when vc

**Comment by jacksongoode** [comment]
When can I download?

**Comment by codewith-luke** [comment]
@Thellior can you look into this?

**Comment by codewith-luke** [comment]
This issue is now resolved. Happy doing business with you.
